default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: root
  password: Toru0424
  host: localhost

development:
  <<: *default
  database: attendance_app_development

test:
  <<: *default
  database: attendance_app_test

production:
  <<: *default
  adapter: mysql2
  database: attendance_app_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
